####
GET http://localhost:3000/api/basic/example
Content-Type: application/json

####
GET http://localhost:3000/api/basic/example/struct
Content-Type: application/json

####
GET http://localhost:3000/api/basic/example/map
Content-Type: application/json

####
GET http://localhost:3000/api/basic/example/ascii
Content-Type: application/json

####
GET http://localhost:3000/api/basic/bindrequest/teacher
Content-Type: application/json

####
GET http://localhost:3000/api/basic/bindrequest/student
Content-Type: application/json

####
GET http://localhost:3000/api/basic/bindrequest/employee
Content-Type: application/json


####
GET http://localhost:3000/api/bindquerystring?name=Danu&age=25&married=false
Content-Type: application/json

####
GET http://localhost:3000/api/bindquerystring
Content-Type: application/json


####
GET http://localhost:3000/api/binduri/Danu/23
Content-Type: application/json


####
GET http://localhost:3000/api/binduri/Danu
Content-Type: application/json
